# Generated by Django 4.0.1 on 2022-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ADDRESS',
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='NAME',
            field=models.CharField(max_length=25),
        ),
    ]
