# Generated by Django 4.0.1 on 2022-02-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_address_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='CONTACT_ID',
        ),
    ]
